New Conjur benchmark

diff --git a/bin/dap b/bin/dap
--- a/bin/dap
+++ b/bin/dap
@@ -86,6 +86,9 @@ Usage: bin/dap [options]:
 
     --wait-for-master                                         Waits for Conjur Master to become healthy.
 
+    --follower-to-master-connection <on/off>                  Pauses or unpauses follower connection to master.
+                                                                (Requires a configured master).
+
 
 EOF
   exit
@@ -753,6 +756,19 @@ function _wait_for_master {
   done
 }
 
+function _follower_to_master_connection {
+  if [ "$1" == "on" ]; then
+      local action="unpause"
+  elif [ "$1" == "off" ]; then
+      local action="pause"
+  else
+      echo "Invalid action. Use either 'on' or 'off'"
+      exit 1
+  fi
+
+  docker container $action conjur-intro-conjur-master-1.mycompany.local-1
+}
+
 _standby_altnames() {
 
   declare -a standby_altnames
@@ -815,6 +831,7 @@ while true ; do
     --version ) shift ; TAG=$1 ; shift ;;
     --k8s-follower-version ) shift ; K8S_FOLLOWER_TAG=$1 ; shift ;;
     --wait-for-master ) CMD='_wait_for_master' ; shift ;;
+    --follower-to-master-connection ) shift ; CMD="_follower_to_master_connection $1" ; shift ;;
      * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
   esac
 done
