Add Follower service prefix to each config job
- In the stdout, it's hard to tell which logs pertain to which follower during a configuration process. This will help with that

diff --git a/bin/dap b/bin/dap
--- a/bin/dap
+++ b/bin/dap
@@ -10,6 +10,7 @@ source ./bin/utils.sh
 # Make sure .env envvars are available
 dotenv > /dev/null 2>&1 || true
 
+FOLLOWER_CONFIG_PIDS=()
 CONJUR_MASTER_PORT=${CONJUR_MASTER_PORT:-443}
 CONJUR_FOLLOWER_PORT=${CONJUR_FOLLOWER_PORT:-450}
 CONJUR_K8S_FOLLOWER_PORT=${CONJUR_K8S_FOLLOWER_PORT:-451}
@@ -92,6 +93,17 @@ Usage: bin/dap [options]:
 
 EOF
   exit
+}
+
+function cleanup_background_jobs() {
+  # NOTE: this will only stop the background jobs for configuring a Follower
+  # from outputting to stdout if a configuration command has begun on the
+  # Follower, that process will remain running within the container. Cleanup of
+  # the containers is left to the --stop command.
+  for pid in "${FOLLOWER_CONFIG_PIDS[@]}"; do
+    echo "Cleaning up Follower configuration job, PID: $pid"
+    pkill -9 -P "$pid"
+  done
 }
 
 function _set_master_multi_node_proxy_config {
@@ -316,6 +328,10 @@ function _setup_followers {
   for ((i=1; i<=FOLLOWER_COUNT; i++))
   do
     _setup_follower "$i" &
+    follower_pid="$!"
+    FOLLOWER_CONFIG_PIDS+=("$follower_pid")
+    echo "Started configuration of Follower conjur-follower-${i}.mycompany.local, PID: $follower_pid"
+
     sleep 0.1
   done
 
@@ -327,14 +343,17 @@ function _setup_followers {
 
 function _setup_follower {
   local follower_number=${1:-1}
+  local follower_service_name
   local start_time
   local end_time
   local execution_time
 
+  follower_service_name="conjur-follower-${follower_number}.mycompany.local"
   start_time=$(date +%s)
+  
 
-  docker compose rm --stop --force "conjur-follower-${follower_number}.mycompany.local"
-  docker compose up --no-deps --detach "conjur-follower-${follower_number}.mycompany.local"
+  docker compose rm --stop --force "$follower_service_name"
+  docker compose up --no-deps --detach "$follower_service_name"
 
   # HACK: Set log level to DEBUG
   # IMPORTANT: this debug hack cannot be applied to the Leader until AFTER
@@ -344,22 +363,22 @@ function _setup_follower {
   #
   # This is because the debug output on the Leader is include in the seedfile,
   # thus corrupting it!
-  _run "conjur-follower-${follower_number}.mycompany.local" "sed -i 's/Logger::INFO/Logger::DEBUG/g' /opt/conjur/evoke/lib/evoke/cli_logger.rb"
-  _run "conjur-follower-${follower_number}.mycompany.local" "cat /opt/conjur/evoke/lib/evoke/cli_logger.rb"
+  _run "$follower_service_name" "sed -i 's/Logger::INFO/Logger::DEBUG/g' /opt/conjur/evoke/lib/evoke/cli_logger.rb"
+  _run "$follower_service_name" "cat /opt/conjur/evoke/lib/evoke/cli_logger.rb"
 
   # Unpack and Configure
-  _run "conjur-follower-${follower_number}.mycompany.local" \
-    "evoke unpack seed /opt/cyberark/dap/seeds/follower-seed-${follower_number}.tar && evoke configure follower --json-attributes-file='/conjur_files/conjur.json' --debug"
+  _run "$follower_service_name" \
+    "evoke unpack seed /opt/cyberark/dap/seeds/follower-seed-${follower_number}.tar && evoke configure follower --json-attributes-file='/conjur_files/conjur.json' --debug" | awk -v follower="$follower_service_name" '{print "[CONFIG " follower "]: " $0}' 
 
   end_time=$(date +%s)
   execution_time=$((end_time-start_time))
 
-  echo "INFO: it took: $execution_time seconds to configure Follower: 'conjur-follower-${follower_number}.mycompany.local'"
+  echo "INFO: it took: $execution_time seconds to configure Follower: '$follower_service_name'"
 
   # Copy certs for HAProxy
-  _run "conjur-follower-${follower_number}.mycompany.local" \
+  _run "$follower_service_name" \
     "cp /opt/conjur/etc/ssl/conjur-follower.mycompany.local.key /opt/conjur/etc/ssl/conjur-follower.mycompany.local.pem.key"
-  _run "conjur-follower-${follower_number}.mycompany.local" \
+  _run "$follower_service_name" \
     "chown 99:99 /opt/conjur/etc/ssl/conjur-follower.mycompany.local.pem.key"
 
 }
@@ -894,5 +913,7 @@ done
 export VERSION=$TAG
 
 create_docker_network
+
+trap cleanup_background_jobs SIGINT
 
 eval $CMD
