Adds certificate flag to import custom certs

diff --git a/bin/dap b/bin/dap
--- a/bin/dap
+++ b/bin/dap
@@ -6,62 +6,25 @@ function _print_help() {
 
 A tool that provides a variety of DAP lifecycle workflows.
 
-Synopsis: bin/dap <command> [command options]
+Synopsis: bin/dap [command options]
 
-Global Options:
+Usage: bin/dap [options]:
 
-    --h, --help                 Shows this help message
-    --stop                      Stops all containers and cleans up cached files
-
-Commands: bin/dap <command>
-
-
-    cluster                     Setup and workflows for a DAP cluster
-    single                      Setup and workflows for a single DAP instance
-
-EOF
-  exit
-}
-
-function _print_cluster_help() {
-  cat << EOF
-
-Provisions a DAP cluster locally using Docker, and run through some common workflows.
-
-Usage: bin/dap cluster [options]
-
-    --create-backup             Generates a backup of the Master. The backup can be found in the system/backup folder
-    --dry-run                   Displays the commands that will be run, without actually running them
-    --disable-auto-failover     Removes nodes into and auto-failover cluster
-    --enable-auto-failover      Enrolls nodes into and auto-failover cluster
-    -h, --help                  Shows this help message
-    --promote-standby           Stops the Master and promotes the first Standby as the new Master
-    --stop                      Stops all containers and cleans up cached files
-    -t, --tag <appliance-tag>   Starts a cluster with a particular appliance (defaults to 5.0-stable)
-
-EOF
-  exit
-}
-
-function _print_single_help() {
-  cat << EOF
-
-Provisions a single DAP instance locally using Docker.
-
-Usage: bin/dap single [options]
-
-    --add-follower-proxy          Adds the follower as a trusted proxy (to enable client IP to be visable in audit logs)
-    --create-backup               Generates a backup of the Master. The backup can be found in the system/backup folder
-    --default                     Starts a single master behind a L4 load balancer (flag not required)
-    --dry-run                     Displays the commands that will be run, without actually running them
-    --fix-11.6-upgrade            Resolves the migration issue present when upgrading to 11.6.
-    --from-backup                 Restores master from a previously created backup
-    -h, --help                    Shows this help message
-    --skip-pull                   Uses the latest local images instead of pulling the latest images
+    --create-backup               Creates a backup|Requires configured master
+    --dry-run                     Print configuration commands with executing
+    --enable-auto-failover        Configures Master cluster with auto-failover (Requires configured master and standbys)
+    --h, --help                   Shows this help message
+    --import-custom-certificates  Imports pre-generated 3rd-party certificates (Requires configured master)
+    --provision-follower          Configures follower behind a Layer 7 load balancer (Requires configured master)
+    --provision-master            Configures a DAP Master with account `default` and password `MySecretP@ss1` behind a Layer 4 load balancer
+    --provision-standbys          Deploys and configures two standbys (Requires configured master)
+    --restore-from-backup         Restores a master from backup|Requires a previously created backup
     --stop                        Stops all containers and cleans up cached files
-    -t, --tag <appliance-tag>     Starts a cluster with a particular appliance (defaults to 5.0-stable)
-    --upgrade-to <appliance-tag>  Upgrades master to the provided version using backup and restore
-    --with-follower               Starts a DAP follower with a Layer 7 load balance
+    --trigger-failover            Stops current master (Requires an auto-failover cluster)
+    --trust-follower-proxy        Adds Follower load balancer as a trusted proxy (Requires a configured follower)
+    --upgrade-master <version>    Restores master from backup (Requires configured master)
+    --version <version>           Version of DAP to use (defaults to latest build)
+
 
 EOF
   exit
@@ -153,7 +116,7 @@ function _configure_master() {
 function _setup_standby() {
   local _standby_number=$1
 
-  docker-compose rm --stop conjur-master-$_standby_number.mycompany.local
+  docker-compose rm --stop --force conjur-master-$_standby_number.mycompany.local
   docker-compose up --no-deps --detach conjur-master-$_standby_number.mycompany.local
 
   # Generate a Seed File
@@ -172,7 +135,7 @@ function _start_standby_synchronization() {
 
 function _setup_follower() {
 
-  docker-compose rm --stop conjur-follower-1.mycompany.local
+  docker-compose rm --stop --force conjur-follower-1.mycompany.local
   docker-compose up --no-deps --detach conjur-follower-1.mycompany.local
 
   # Generate Seed file
@@ -182,6 +145,8 @@ function _setup_follower() {
   # Unpack and Configure
   _run conjur-follower-1.mycompany.local \
     "evoke unpack seed /opt/cyberark/dap/seeds/follower-seed.tar && evoke configure follower"
+
+  _start_l7_load_balancer
 }
 
 #
@@ -226,9 +191,9 @@ function _reload_container {
 }
 
 function _setup_standbys {
-  # _setup_standby 2
-  # _setup_standby 3
-  # _start_standby_synchronization
+  _setup_standby 2
+  _setup_standby 3
+  _start_standby_synchronization
 
   # Reload load balancer to serve cluster
   _set_master_multi_node_proxy_config
@@ -239,9 +204,6 @@ function _basic_cluster() {
   _start_cluster
   _configure_master
   _setup_standbys
- 	# _setup_standby 2
-  # _setup_standby 3
-  # _start_standby_synchronization
   _setup_follower
   _start_l7_load_balancer
   echo "Master Cluster available at: 'https://localhost'"
@@ -281,17 +243,19 @@ function _disable_autofailover {
 }
 
 function _enable_autofailover {
+
+  autofailover=$(curl -k https://conjur-master-1.mycompany.local/info | jq .configuration.conjur.cluster_name)
+  if [[ $autofailover = 'production' ]]; then
+    _run conjur-master-2.mycompany.local "evoke cluster enroll --reenroll --cluster-machine-name conjur-master-2.mycompany.local --master-name conjur-master-1.mycompany.local production"
+    _run conjur-master-3.mycompany.local "evoke cluster enroll --reenroll --cluster-machine-name conjur-master-3.mycompany.local --master-name conjur-master-1.mycompany.local production"
+  else
     _cli root "policy/base.yml"
     _cli conjur/cluster policy/cluster.yml
 
     _run conjur-master-1.mycompany.local "evoke cluster enroll --cluster-machine-name conjur-master-1.mycompany.local production"
     _run conjur-master-2.mycompany.local "evoke cluster enroll --cluster-machine-name conjur-master-2.mycompany.local --master-name conjur-master-1.mycompany.local production"
     _run conjur-master-3.mycompany.local "evoke cluster enroll --cluster-machine-name conjur-master-3.mycompany.local --master-name conjur-master-1.mycompany.local production"
-}
-
-function _re_enable_autofailover {
-  _run conjur-master-2.mycompany.local "evoke cluster enroll --reenroll --cluster-machine-name conjur-master-2.mycompany.local --master-name conjur-master-1.mycompany.local production"
-  _run conjur-master-3.mycompany.local "evoke cluster enroll --reenroll --cluster-machine-name conjur-master-3.mycompany.local --master-name conjur-master-1.mycompany.local production"
+  fi
 }
 
 function _stop_replication() {
@@ -313,6 +277,11 @@ function _stop_and_rename() {
 
 function _upgrade_via_backup_restore() {
   upgrade_to="$1"
+
+  autofailover=$(curl -k https://conjur-master-1.mycompany.local/info | jq .configuration.conjur.cluster_name)
+  if [[ $autofailover = 'production' ]]; then
+    _disable_autofailover
+  fi
   _upgrade_master_via_backup_restore $upgrade_to
 
   # redeploy standbys with the new container image and a new seed file from the master
@@ -367,6 +336,12 @@ function _add_follower_proxy() {
     "evoke proxy add 12.16.23.15"
 }
 
+function _trigger_master_failover_failover {
+  _run conjur-master-1.mycompany.local \
+    "sv stop conjur"
+  echo 'Auto-failover takes about a minute to complete.'
+}
+
 function _fix_11_6_0 {
   _run conjur-master-1.mycompany.local \
     "sv stop conjur"
@@ -378,76 +353,42 @@ function _fix_11_6_0 {
     "sv start conjur"
 }
 
+function _import_certificates {
+  local cert_path='/opt/cyberark/dap/configuration/certificates'
+  _run conjur-master-1.mycompany.local \
+    "evoke ca import --root $cert_path/ca-chain.cert.pem"
+  _run conjur-master-1.mycompany.local \
+    "evoke ca import --key $cert_path/conjur-master.mycompany.local.key.pem --set $cert_path/conjur-master.mycompany.local.cert.pem"
+  _run conjur-master-1.mycompany.local \
+    "evoke ca import --key $cert_path/conjur-follower.mycompany.local.key.pem $cert_path/conjur-follower.mycompany.local.cert.pem"
+}
+
 TAG=5.0-stable
 DRY_RUN=false
 PULL_IMAGES=true
 CMD=""
 to_version=""
 
-if [[ "$1" = "cluster" ]]; then
-  shift
-  CMD="_basic_cluster"
-
-  while true ; do
-    case "$1" in
-      --create-backup ) CMD='_create_backup' ; shift ;;
-      --default ) CMD='_basic_cluster' ; shift ;;
-      --dry-run ) DRY_RUN=true ; shift ;;
-      --disable-auto-failover ) CMD='_disable_autofailover' ; shift ;;
-      --enable-auto-failover ) CMD='_enable_autofailover' ; shift ;;
-      --promote-standby ) CMD='_perform_promotion' ; shift ;;
-      --redeploy-standbys ) CMD='_setup_standbys' ; shift ;;
-      --stop ) _stop ; exit ;;
-      --skip-pull ) PULL_IMAGES=false ; shift ;;
-      -t | --tag ) shift ; TAG=$1 ; shift ;;
-      -h | --help ) _print_cluster_help ; shift ;;
-       * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
-    esac
-  done
-elif [[ "$1" = "single" ]]; then
-  shift
-  CMD="_single_master"
-
-  while true ; do
-    case "$1" in
-      --add-follower-proxy ) CMD='_add_follower_proxy' ; shift ;;
-      --create-backup ) CMD='_create_backup' ; shift ;;
-      --default ) CMD='_single_master' ; shift ;;
-      --dry-run ) DRY_RUN=true ; shift ;;
-      --fix-11.6-upgrade ) CMD="_fix_11_6_0"; shift ;;
-      --from-backup ) CMD="_restore_from_backup" ; shift ;;
-      -h | --help ) _print_single_help ; shift ;;
-      --skip-pull ) PULL_IMAGES=false ; shift ;;
-      --stop ) _stop ; exit ;;
-      -t | --tag ) shift ; TAG=$1 ; shift ;;
-      --upgrade-to ) shift ; CMD="_upgrade_via_backup_restore $1" ; shift ;;
-      --with-follower ) CMD='_single_master_follower' ; shift ;;
-       * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
-    esac
-  done
-
-else
-  while true ; do
-    case "$1" in
-      --version ) shift ; TAG=$1 ; shift ;;
-      --dry-run ) DRY_RUN=true ; shift ;;
-      -h | --help ) _print_help ; shift ;;
-      --provision-master ) CMD='_single_master' ; shift ;;
-      # --import-certificates ) CMD='' ; shift ;;
-      --provision-standbys ) CMD='_setup_standbys' ; shift ;;
-      --enable-auto-failover ) CMD='_enable_autofailover' ; shift ;;
-      --disable-auto-failover ) CMD='_disable_autofailover' ; shift ;;
-      --re-enable-auto-failover ) CMD='_re_enable_autofailover' ; shift ;;
-      # --provision-follower ) _setup_follower ; _start_l7_load_balancer ; shift ;;
-      --upgrade-master ) CMD='_upgrade_via_backup_restore' ; shift ;;
-      # --trigger-failover ) ; shift ;;
-      --create-backup ) CMD='_create_backup' ; shift ;;
-      --restore-from-backup ) CMD='_restore_from_backup' ; shift ;;
-      --stop ) _stop ; shift ;;
-       * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
-    esac
-  done
-fi
+while true ; do
+  case "$1" in
+    --provision-master ) CMD='_single_master' ; shift ;;
+    --import-custom-certificates ) CMD='_import_certificates' ; shift ;;
+    --provision-standbys ) CMD='_setup_standbys' ; shift ;;
+    --enable-auto-failover ) CMD='_enable_autofailover' ; shift ;;
+    --provision-follower ) CMD='_setup_follower' ; shift ;;
+    --upgrade-master ) shift ; TAG=$1 CMD='_upgrade_via_backup_restore' ; shift ;;
+    --version ) shift ; TAG=$1 ; shift ;;
+    --dry-run ) DRY_RUN=true ; shift ;;
+    -h | --help ) _print_help ; shift ;;
+    # --disable-auto-failover ) CMD='_disable_autofailover' ; shift ;;
+    --trigger-failover ) CMD='_trigger_master_failover_failover' ; shift ;;
+    --create-backup ) CMD='_create_backup' ; shift ;;
+    --restore-from-backup ) CMD='_restore_from_backup' ; shift ;;
+    --trust-follower-proxy ) CMD='_add_follower_proxy' ; shift ;;
+    --stop ) _stop ; shift ;;
+     * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
+  esac
+done
 
 export VERSION=$TAG
 
