Add replication test suite
- This leverages the newly created test scripts
- The backup is provided by the Appliance repository:`appliance/tree/master/test/load/backup`. It is provided here because the new appliance repo cannot be sourced from these executors
- Configuring a Leader, or restoring from backup now automatically includes the conjur.json config file
- This conjur.json config is updated to allow scaling a large number of Followers (~EST. 100)
- Disable the test-secret-replication script

Move backups into system/backup

- There are read/write issues with copying these files from some source directory to this directory

Change default for REPLICATION_FOLLOWER_COUNT to 2

- Since tests compare the state of multiple Followers to the Leader it makes sense that a minimum of 2 Followers is used

SQUASH update default followers to 2

Remove unused variable

diff --git a/bin/dump-appliance-health-and-info b/bin/dump-appliance-health-and-info
--- a/bin/dump-appliance-health-and-info
+++ b/bin/dump-appliance-health-and-info
@@ -9,34 +9,38 @@ set -o pipefail
 # `tmp/appliance/info` directories. If there is no response, this indicates
 # a node failure configure / deploy, and this script will fail.
 #
-# ./bin/dump-appliance-health-and-info 1
-# ./bin/dump-appliance-health-and-info 5
-# ./bin/dump-appliance-health-and-info 10
+# ./bin/dump-appliance-health-and-info --follower-count 1
+# ./bin/dump-appliance-health-and-info --follower-count 5
+# ./bin/dump-appliance-health-and-info --follower-count 10
 
 # Always work from repo root directory
 cd "$(dirname ${0})/..";
 
 source ./bin/utils.sh
 
-HEALTH_LOG_DIR="tmp/appliance/health"
+LOG_PREFIX=$(date -u +"%Y-%m-%dT%H:%M:%S.000+00:00")
+HEALTH_LOG_DIR="tmp/appliance/health-$LOG_PREFIX"
 LEADER_HEALTH_LOG_DIR="$HEALTH_LOG_DIR/leader"
 FOLLOWER_HEALTH_LOG_DIR="$HEALTH_LOG_DIR/follower"
 
-INFO_LOG_DIR="tmp/appliance/info"
+INFO_LOG_DIR="tmp/appliance-$LOG_PREFIX/info"
 LEADER_INFO_LOG_DIR="$INFO_LOG_DIR/leader"
 FOLLOWER_INFO_LOG_DIR="$INFO_LOG_DIR/follower"
 
-FOLLOWER_COUNT="$1"
+NO_FAIL="false"
+FOLLOWER_COUNT=
 
 # Use this to hide WARN from docker compose...
 # WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string. 
 export VERSION=
 
 main(){
+  echo "Beginning script: $0"
+
   is_failure_detected_globally="false"
 
   if [[ -z "$FOLLOWER_COUNT" ]]; then
-    echo "FATAL: FOLLOWER_COUNT must be specified as \$1"
+    echo "FATAL: FOLLOWER_COUNT must be specified as --follower-count"
     exit 1
   fi
 
@@ -61,7 +65,7 @@ main(){
   do
     FOLLOWER_HOSTNAME="conjur-follower-${i}.mycompany.local"
 
-    container_id=$(docker-compose ps -q $FOLLOWER_HOSTNAME)
+    container_id=$(docker compose ps -q $FOLLOWER_HOSTNAME)
     if [ -z "$container_id" ]; then
       echo "\tWARNING: No container ID found for service '$FOLLOWER_HOSTNAME' (it is not running), skipping!"
       continue
@@ -71,24 +75,32 @@ main(){
     output=$(docker compose exec "conjur-follower-${i}.mycompany.local" curl -s -k https://localhost/health | sed 's/^/\t/')
     if [[ -n "$output" ]]; then
       echo "$output" | tee "$FOLLOWER_HEALTH_LOG_DIR/conjur-follower-${i}-health.log"
-      is_failure_detected_globally="true"
     else
       echo -e "\tERROR: Failed to fetch health for '$FOLLOWER_HOSTNAME'"
+      is_failure_detected_globally="true"
     fi
     
     output=$(docker compose exec "conjur-follower-${i}.mycompany.local" curl -s -k https://localhost/info | sed 's/^/\t/')
     if [[ -n "$output" ]]; then
       echo "$output" | tee "$FOLLOWER_INFO_LOG_DIR/conjur-follower-${i}-info.log"
-      is_failure_detected_globally="true"
     else
       echo -e "\tERROR: Failed to fetch info for '$FOLLOWER_HOSTNAME'"
+      is_failure_detected_globally="true"
     fi
   done
 
-  if [ "$is_failure_detected_globally" = "true" ]; then
-    echo "FATAL: An error was detected in at leats one node, see above."
+  if [ "$is_failure_detected_globally" = "true" ] && [ "$NO_FAIL" = "false" ] ; then
+    echo "FATAL: An error was detected in at least one node, see above."
     exit 1
   fi
 }
 
-main "$@"
+while true ; do
+  case "$1" in
+    --no-fail ) NO_FAIL='true' ; shift ;;
+    --follower-count ) shift; FOLLOWER_COUNT="$1" ; shift ;;
+     * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
+  esac
+done
+
+main
diff --git a/bin/test-secret-replication b/bin/test-secret-replication
--- a/bin/test-secret-replication
+++ b/bin/test-secret-replication
@@ -2,7 +2,7 @@
 
 # USAGE
 #
-# Given a NUMBER_OF_SECRETS, dynamically generates a Conjur Policy branch
+# Given a SECRET_COUNT, dynamically generates a Conjur Policy branch
 # for the given counter. Each secret is set on the Leader, and then checked
 # on each of the Followers in parallel (with up to 5 retries). If any one
 # Follower fails to replicate the secret, this script will fail.
@@ -11,10 +11,10 @@
 # remain after the script is run. This is intentional so that
 # `test-table-rows-match` has data to work with.
 #
-# ./test-secret-replication.sh <NUMBER_OF_SECRETS> <FOLLOWER_COUNT>
-# ./test-secret-replication.sh 1 1
-# ./test-secret-replication.sh 5 5
-# ./test-secret-replication.sh 5 10
+# ./bin/test-secret-replication.sh --secret-count <SECRET_COUNT> --follower-count <FOLLOWER_COUNT>
+# ./bin/test-secret-replication.sh --secret-count 1 --follower-count 1
+# ./bin/test-secret-replication.sh --secret-count 5 --follower-count 5
+# ./bin/test-secret-replication.sh --secret-count 5 --follower-count 10
 #
 
 DOCKER_LEADER_CONTAINER="conjur-master-1.mycompany.local"
@@ -22,27 +22,31 @@ CONJUR_USER="admin"
 CONJUR_ACCOUNT="demo"
 CONJUR_PASSWORD="MySecretP@ss1"
 BASE_POLICY_BRANCH="replication-test"
-TEST_POLICY_BRANCH_PREFIX="secret-"
-MAX_ATTEMPTS=5
+TEST_POLICY_BRANCH_PREFIX="policy-"
+MAX_ATTEMPTS=
 
 # Use this to hide WARN from docker compose...
 # WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string. 
 export VERSION=
 
+FOLLOWER_COUNT=
+SECRET_COUNT=
 
 main() {
-  NUMBER_OF_SECRETS="$1"
-  FOLLOWER_COUNT="$2"
+  echo "Beginning script: $0"
+  
+  if [[ -z "$MAX_ATTEMPTS" ]]; then
+    echo "FATAL: MAX_ATTEMPTS must be specified as --max-attempts"
+    exit 1
+  fi
 
-  mkdir -p ./policy/bulk
-
-  if [[ -z "$NUMBER_OF_SECRETS" ]]; then
-    echo "FATAL: NUMBER_OF_SECRETS must be specified as \$1"
+  if [[ -z "$SECRET_COUNT" ]]; then
+    echo "FATAL: SECRET_COUNT must be specified as --secret-count"
     exit 1
   fi
 
   if [[ -z "$FOLLOWER_COUNT" ]]; then
-    echo "FATAL: FOLLOWER_COUNT must be specified as \$2"
+    echo "FATAL: FOLLOWER_COUNT must be specified as --follower-count"
     exit 1
   fi
 
@@ -52,14 +56,26 @@ main() {
     exit 1
   fi
 
+  echo "Will attempt to load '${SECRET_COUNT}' policies/secrets against '${FOLLOWER_COUNT}' Followers with a max retry of '${MAX_ATTEMPTS}' attempts..."
+
   # Reset the base policy branch
+  echo "Replacing base policy..."
   replace_base_policy
 
   # Create the base branch where tests will take place on...
+  echo "Loading base policy..."
   load_base_policy
 
-  for i in $(seq 1 "$NUMBER_OF_SECRETS"); do
-    echo "Loading secret $i..."
+  for i in $(seq 1 "$SECRET_COUNT"); do
+    # Refresh the Conjur Access Token...
+    TOKEN=$(get_conjur_access_token)
+    if [[ -z "$TOKEN" ]]; then
+      echo "FATAL: Failed to get Conjur Access Token!"
+      exit 1
+    fi
+
+    echo "Loading secret $i/$SECRET_COUNT..."
+    echo "[DEBUG] USING TOKEN: $TOKEN"
     DYNAMIC_BRANCH="${TEST_POLICY_BRANCH_PREFIX}${i}"
     POLICY_FILE=$(get_dynamic_policy "$i")
 
@@ -72,41 +88,71 @@ main() {
       exit 1
     fi
     echo -e "\nDynamic policy '$DYNAMIC_BRANCH' was loaded successfully."
-    
+
     # Generate a timestamp: Unix timestamp in seconds + milliseconds (last 3 digits)
     SECRET_VALUE=$(date +%s)$(awk -v min=0 -v max=999 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
     SECRET_IDENTIFIER=$(urlencode_forward_slashes_only "${BASE_POLICY_BRANCH}/${DYNAMIC_BRANCH}/secret_${i}")
 
-    echo "Updating secret '$SECRET_IDENTIFIER' to: $SECRET_VALUE"
+    echo "In the Leader, updating secret '$SECRET_IDENTIFIER' to: $SECRET_VALUE"
     set_secret "$SECRET_IDENTIFIER" "$SECRET_VALUE"
 
     if [ $? -ne 0 ]; then
-      echo -e "\nFATAL: Failed to set secret!"
+      echo -e "\nFATAL: Failed to set secret in the Leader!"
       exit 1
     fi
-    echo -e "\nSuccessfully was set successfully."
+    echo -e "\nSecret was set successfully in the Leader!"
 
     pids=()
     for ((j=1; j<=FOLLOWER_COUNT; j++))
     do
       # Execute the following in parallel...
       FOLLOWER_HOSTNAME="conjur-follower-${j}.mycompany.local"
-      echo "[$FOLLOWER_HOSTNAME] (Attempt: $j/$MAX_ATTEMPTS) - Starting job to set secret on follower $FOLLOWER_HOSTNAME..."
+      echo "[$FOLLOWER_HOSTNAME] Starting job to set secret on follower $FOLLOWER_HOSTNAME..."
       (
         for ((k=1; k<=MAX_ATTEMPTS; k++))
         do
+          # This test has been encountering issues where:
+          #
+          # 1) A Token provided by a Leader is seen as invalid, but the token
+          # works for other Followers. This is seen in the Follower log:
+          #
+          # conjur-follower-3.mycompany.local-1  | <14>1 2024-06-04T22:37:02.000+00:00 ffe6d49725ac conjur-possum 1058 - [meta sequenceId="39"] [origin=12.16.23.11] [request_id=bc42f74e-3da1-478e-b47d-b103b7745f33] [tid=1070] Started GET "/secrets/demo/variable/replication-test%2Fpolicy-1%2Fsecret_1" for 12.16.23.11 at 2024-06-04 22:37:02 +0000
+          # conjur-follower-3.mycompany.local-1  | <13>1 2024-06-04T22:37:03.622+00:00 ffe6d49725ac nginx - - [meta sequenceId="40"] 12.16.23.11 "-" "GET /secrets/demo/variable/replication-test%2Fpolicy-1%2Fsecret_1 HTTP/1.1" 401 27 "-" "curl/7.81.0" 0.028 0.028
+          #
+          # 2) A token provided by a Follower is seen as invalid. This is seen
+          # in the Follower log:
+          #
+          # conjur-follower-2.mycompany.local-1  | <14>1 2024-06-04T22:57:32.000+00:00 9abb871007d8 conjur-possum 1071 - [meta sequenceId="171"] [origin=12.16.23.11] [request_id=174d748f-60f7-493e-802f-b2de7aaf16c3] [tid=1094] Started GET "/authn/demo/login" for 12.16.23.11 at 2024-06-04 22:57:32 +0000
+          # conjur-follower-2.mycompany.local-1  | <14>1 2024-06-04T22:57:32.000+00:00 9abb871007d8 conjur-possum 1071 - [meta sequenceId="172"] [origin=12.16.23.11] [request_id=174d748f-60f7-493e-802f-b2de7aaf16c3] [tid=1094] Processing by AuthenticateController#login as */*
+          # conjur-follower-2.mycompany.local-1  | <14>1 2024-06-04T22:57:32.000+00:00 9abb871007d8 conjur-possum 1071 - [meta sequenceId="173"] [origin=12.16.23.11] [request_id=174d748f-60f7-493e-802f-b2de7aaf16c3] [tid=1094]   Parameters: {:controller=>"authenticate", :action=>"login", :authenticator=>"authn", :account=>"demo"}
+          # conjur-follower-2.mycompany.local-1  | <14>1 2024-06-04T22:57:32.000+00:00 9abb871007d8 conjur-possum 1071 - [meta sequenceId="174"] [origin=12.16.23.11] [request_id=174d748f-60f7-493e-802f-b2de7aaf16c3] [tid=1094] CONJ00047I Login Error: #<Errors::Authentication::Security::AccountNotDefined: CONJ00008E Account 'demo' is not defined in Conjur>
+          #
+          # This seems to indicate that a Follower might be in the process of
+          # replicating (healthily) still... so increase MAX_ATTEMPTS
+          # reasonably.
+          #
+          TOKEN_FROM_FOLLOWER=$(get_conjur_access_token_from_follower "$FOLLOWER_HOSTNAME")
+
           echo "[$FOLLOWER_HOSTNAME] (Attempt: $k/$MAX_ATTEMPTS) - Begin checking secret '$SECRET_IDENTIFIER' on follower '$FOLLOWER_HOSTNAME'..."
+          echo "[$FOLLOWER_HOSTNAME] [DEBUG] USING TOKEN_FROM_FOLLOWER: $TOKEN_FROM_FOLLOWER"
+
           FOLLOWER_SECRET_VALUE=$(get_secret_from_follower "$FOLLOWER_HOSTNAME" "$SECRET_IDENTIFIER")
 
           if [[ "$FOLLOWER_SECRET_VALUE" == "$SECRET_VALUE" ]]; then
             echo "[$FOLLOWER_HOSTNAME] (Attempt: $k/$MAX_ATTEMPTS) - Successfully replicated secret '$SECRET_IDENTIFIER' with value '$FOLLOWER_SECRET_VALUE' to follower '$FOLLOWER_HOSTNAME'."
             break
-          elif [[ "$k" -eq 5 ]]; then
+          elif [[ "$k" -eq $MAX_ATTEMPTS ]]; then
             echo "[$FOLLOWER_HOSTNAME] (Attempt: $k/$MAX_ATTEMPTS) - FATAL: Follower $FOLLOWER_HOSTNAME failed to replicate secret_$i. Expected '$SECRET_IDENTIFIER' to be '$SECRET_VALUE', got '$FOLLOWER_SECRET_VALUE'..."
+
+            # Make visible the situation documented above
+            if [[ "$FOLLOWER_SECRET_VALUE" == "Unauthorized: Invalid token" ]]; then
+              echo "[$FOLLOWER_HOSTNAME] (Attempt: $k/$MAX_ATTEMPTS) - WARNING: it seems like the Follower is still replicating, and the resources associated with this token are not yet available. This might be a transient issue that can be resolved by increasing 'MAX_ATTEMPTS', or the Follower might be unhealthy."
+            fi
             exit 1
           fi
-          echo "[$FOLLOWER_HOSTNAME] (Attempt: $k/$MAX_ATTEMPTS) - Retrying in 0.5 seconds..."
-          sleep 0.5
+
+          echo "[$FOLLOWER_HOSTNAME] (Attempt: $k/$MAX_ATTEMPTS) - Retrying in 3 seconds..."
+          sleep 3
         done
       ) &
       pids+=("$!")
@@ -140,7 +186,7 @@ EOF
       --request PUT \
       --header 'Authorization: Token token=\"$TOKEN\"' \
       --data '$POLICY_BODY' \
-      https://localhost/policies/$CONJUR_ACCOUNT/policy/$BASE_POLICY_BRANCH
+      https://localhost/policies/$CONJUR_ACCOUNT/policy/root
   "
 
 
@@ -177,6 +223,18 @@ get_conjur_access_token() {
         --request POST \
         --data "$API_KEY" \
         "https://localhost/authn/$CONJUR_ACCOUNT/$CONJUR_USER/authenticate" | base64 | tr -d "[:space:]"
+}
+
+get_conjur_access_token_from_follower() {
+  TARGET_HOST="$1"
+  API_KEY=$(docker compose exec "$DOCKER_LEADER_CONTAINER" curl --silent --user "$CONJUR_USER:$CONJUR_PASSWORD" -k "https://$TARGET_HOST/authn/$CONJUR_ACCOUNT/login")
+  docker compose exec "$DOCKER_LEADER_CONTAINER" curl \
+        --max-time 3 \
+        --silent \
+        --insecure \
+        --request POST \
+        --data "$API_KEY" \
+        "https://$TARGET_HOST/authn/$CONJUR_ACCOUNT/$CONJUR_USER/authenticate" | base64 | tr -d "[:space:]"
 }
 
 load_dynamic_policy() {
@@ -267,4 +325,14 @@ urlencode_forward_slashes_only() {
     echo "$string" | sed 's|/|%2F|g'
 }
 
-main "$@"
+while true ; do
+  case "$1" in
+    --follower-count ) shift; FOLLOWER_COUNT="$1" ; shift ;;
+    --secret-count ) shift; SECRET_COUNT="$1" ; shift ;;
+    --max-attempts ) shift; MAX_ATTEMPTS="$1" ; shift ;;
+     * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
+  esac
+done
+
+main
+
