Add log test for K8S Follower
- Parses the Leader and K8S Follower logs for replication slot errors
- Decouple the logging of Appliance Leader and Followers, and creation of artifacts, making referencing these logs simpler in log related tests
- Remove superfluous sleeps when dumping K8S resources
- Dump K8S logs in the right place

diff --git a/bin/dump-appliance-follower-logs b/bin/dump-appliance-follower-logs
--- a/bin/dump-appliance-follower-logs
+++ b/bin/dump-appliance-follower-logs
@@ -1,16 +1,15 @@
-#!/bin/bash
+#!/bin/bash -x
 
 # USAGE
 #
-# Dumps the logs of the running Leader and all Followers up to the given
-# FOLLOWER_COUNT. If the container is not running, no log is printed, and
-# indicating a failure to configure / deploy a container, and this script will
-# fail.
+# Dumps the logs of the running Appliance Followers. If a container is not
+# running, no log is printed, and indicating a failure to configure / deploy a
+# container, and this script will fail.
 #
-# ./bin/dump-appliance-logs --follower-count 1
-# ./bin/dump-appliance-logs --follower-count 5
-# ./bin/dump-appliance-logs --follower-count 10
-# ./bin/dump-appliance-logs --no-fail --follower-count 10
+# ./bin/appliance-follower-logs --log-directory tmp --follower-count 1
+# ./bin/appliance-follower-logs --log-directory tmp --follower-count 5
+# ./bin/appliance-follower-logs --log-directory tmp --follower-count 10
+# ./bin/appliance-follower-logs --log-directory tmp --no-fail --follower-count 10
 
 set -e
 
@@ -20,9 +19,7 @@ cd "$(dirname ${0})/..";
 source ./bin/functions
 source ./bin/utils.sh
 
-LOG_DIR="$(appliance_log_dir)/logs"
-LEADER_LOG_DIR="$LOG_DIR/leader"
-FOLLOWER_LOG_DIR="$LOG_DIR/follower"
+LOG_DIR=
 NO_FAIL="false"
 FOLLOWER_COUNT=
 LEADER_COUNT=3
@@ -31,15 +28,32 @@ LEADER_COUNT=3
 # WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
 export VERSION=
 
+finish() {
+  if [ "$NO_FAIL" = "true" ]; then
+    exit 0
+  fi
+  exit "$1"
+}
+
 main(){
-  is_failure_detected_globally="false"
+  local is_failure_detected_globally="false"
+
+  trap 'finish $?' EXIT
 
   echo "Beginning script: $0"
 
-  if [[ -z "$FOLLOWER_COUNT" ]]; then
-    echo "FATAL: FOLLOWER_COUNT must be specified as --follower-count"
+  if [[ -z "$LOG_DIR" ]]; then
+    echo "FATAL: Argument '--log-directory' must be provided!"
     exit 1
   fi
+
+  if [[ -z "$FOLLOWER_COUNT" ]]; then
+    echo "FATAL: Argument '--follower-count' must be provided!"
+    exit 1
+  fi
+
+  echo "Creating log directory: $LOG_DIR..."
+  mkdir -p "$LOG_DIR"
 
   if [ "$NO_FAIL" = "true" ]; then
     echo "NO_FAIL is specified, this script will not fail if a container is not running."
@@ -65,9 +79,10 @@ main(){
   echo "Dumping Leader reconfigure logs at: $LEADER_LOG_DIR"
   docker compose logs "conjur-master.mycompany.local" > "$LEADER_LOG_DIR/haproxy.log"
 
-  echo "Dumping Follower Logs at: $FOLLOWER_LOG_DIR"
+  echo "Dumping Follower Logs at: $LOG_DIR"
   for ((i=1; i<=FOLLOWER_COUNT; i++))
   do
+    local log_file_path="$LOG_DIR/conjur-follower-${i}.log"
     FOLLOWER_HOSTNAME="conjur-follower-${i}.mycompany.local"
 
     container_id=$(docker compose ps -q $FOLLOWER_HOSTNAME)
@@ -77,8 +92,8 @@ main(){
       continue
     fi
 
-    echo "Dumping logs for '$FOLLOWER_HOSTNAME'"
-    docker compose logs "$FOLLOWER_HOSTNAME" > "$FOLLOWER_LOG_DIR/conjur-follower-${i}.log"
+    echo "Dumping logs for '$FOLLOWER_HOSTNAME' at: $log_file_path..."
+    docker compose logs "$FOLLOWER_HOSTNAME" > "$log_file_path"
   done
 
   if [ "$is_failure_detected_globally" = "true" ] && [ "$NO_FAIL" = "false" ] ; then
@@ -91,6 +106,7 @@ main(){
 while true ; do
   case "$1" in
     --no-fail ) NO_FAIL='true' ; shift ;;
+    --log-directory ) shift; LOG_DIR="$1" ; shift ;;
     --follower-count ) shift; FOLLOWER_COUNT="$1" ; shift ;;
      * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
   esac
diff --git a/bin/test-leader-logs-for-replication-slot-errors b/bin/test-leader-logs-for-replication-slot-errors
--- a/bin/test-leader-logs-for-replication-slot-errors
+++ b/bin/test-leader-logs-for-replication-slot-errors
@@ -10,7 +10,7 @@ set -o pipefail
 #
 # NOTE: Leader and Follower logs are tested for different patterns/cases.
 #
-# ./bin/test-leader-logs-for-replication-slot-errors
+# ./bin/test-leader-logs-for-replication-slot-errors --log-directory tmp
 #
 
 # Always work from repo root directory
@@ -19,18 +19,32 @@ cd "$(dirname ${0})/..";
 source ./bin/functions
 source ./bin/utils.sh
 
-LOG_DIR="$(appliance_log_dir)/logs"
-LEADER_LOG_DIR="$LOG_DIR/leader"
+LOG_DIR=
 
 main(){
   is_failure_detected_globally="false"
   failed_logs=()
 
-  for file in "$LEADER_LOG_DIR"/*
+  if [[ -z "$LOG_DIR" ]]; then
+    echo "FATAL: Argument '--log-directory' must be provided!"
+    exit 1
+  fi
+
+  if [ ! -d "$LOG_DIR" ]; then
+    echo "FATAL: Directory does not exist: $LOG_DIR"
+    exit 1
+  fi
+
+  for file in "$LOG_DIR"/*
   do
     is_leader_failure_detected="false"
 
     echo "Testing log file: $file..."
+
+    if [ ! -s "$file" ]; then
+      echo "ERROR: log file does not exist or is empty, and cannot be tested: $file..."
+      is_failure_detected_globally="true"
+    fi
 
     if grep -n -E 'ERROR:  replication slot "pg_[0-9]+_sync_[0-9]+_[0-9]+" does not exist' "$file" | sed 's/^/\t/'; then
       is_leader_failure_detected="true"
@@ -56,4 +70,11 @@ main(){
   echo "DONE."
 }
 
-main "$@"
+while true ; do
+  case "$1" in
+    --log-directory ) shift; LOG_DIR="$1" ; shift ;;
+     * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
+  esac
+done
+
+main
