Improve visibility on replication-test for (appliance followers)
- Test output is now summarized at the end of the script
- Remove superfluous resource monitoring; in the past this was done to identify in jenkins if a pgidentifer was  causing `evoke configure follower` to hang on older versions of the appliance, and it turns out it is true. This is before we had a way to timeout configuration of multiple followers, which rendered us unable to capture log artifacts in aborted jenkins builds; since then, we've enabled that, and can obtain those artifacts now, so no need to render this resource monitoring output

diff --git a/bin/replication-test b/bin/replication-test
--- a/bin/replication-test
+++ b/bin/replication-test
@@ -49,6 +49,12 @@ export VERSION
 
 pid=""
 
+# Initialize two indexed arrays to hold the test command names and their
+# exit codes
+TEST_COMMANDS=()
+EXIT_CODES_FIRST_RUN=()
+EXIT_CODES_SECOND_RUN=()
+
 finish() {
   # If a background process PID was stored, kill it (do not fail script if it is not found)
   if [ -n "$pid" ]; then
@@ -57,11 +63,27 @@ finish() {
   fi
 
   ./bin/create-log-artifacts --log-directory "$LOG_DIR" --follower-count  "${FOLLOWER_COUNT}"
+  print_test_suite_summary
+
   teardown_compose_environment
+  determine_exit_code "$exit_code"
+  exit $?
 }
 
 main(){
+  local leader_log_dir="$LOG_DIR/logs/leader"
+  local follower_log_dir="$LOG_DIR/logs/follower"
+
   trap finish EXIT
+
+  TEST_COMMANDS+=("./bin/test-follower-pg-identifier --follower-count \"${FOLLOWER_COUNT}\"")
+  TEST_COMMANDS+=("./bin/dump-appliance-health-and-info --follower-count \"${FOLLOWER_COUNT}\"")
+  TEST_COMMANDS+=("./bin/test-secret-replication --max-attempts \"${MAX_ATTEMPTS}\" --policy-count \"${POLICY_COUNT}\" --secret-count \"${SECRET_COUNT}\" --follower-count \"${FOLLOWER_COUNT}\"")
+  TEST_COMMANDS+=("./bin/test-table-rows-match --follower-count \"${FOLLOWER_COUNT}\" --max-attempts \"${MAX_ATTEMPTS}\"")
+  TEST_COMMANDS+=("./bin/dump-leader-logs --no-fail --log-directory \"$leader_log_dir\"")
+  TEST_COMMANDS+=("./bin/dump-appliance-follower-logs --no-fail --log-directory \"$follower_log_dir\" --follower-count \"${FOLLOWER_COUNT}\"")
+  TEST_COMMANDS+=("./bin/test-leader-logs-for-replication-slot-errors --log-directory \"$leader_log_dir\"")
+  TEST_COMMANDS+=("./bin/test-appliance-follower-logs-for-replication-slot-errors --log-directory \"$follower_log_dir\"")
 
   if [ "$USE_EXISTING_ENVIRONMENT" = "true" ]; then
     echo "USE_EXISTING_ENVIRONMENT is set to '$USE_EXISTING_ENVIRONMENT'... Setting RESOURCE_INTERVAL to '1'..."
@@ -116,16 +138,17 @@ main(){
     fi
   fi
 
-  # Begin test suite
-  echo "Gathering test results..."
-  ./bin/test-follower-pg-identifier --follower-count "${FOLLOWER_COUNT}"
-  ./bin/dump-appliance-health-and-info --follower-count "${FOLLOWER_COUNT}"
-  ./bin/test-table-rows-match --follower-count "${FOLLOWER_COUNT}" --max-attempts "${MAX_ATTEMPTS}"
-
-  # These the test below depends on the appliance logs...
-  ./bin/dump-leader-logs --no-fail --log-directory "$LOG_DIR/logs/leader"
-  ./bin/dump-appliance-follower-logs --no-fail --log-directory "$LOG_DIR/logs/follower" --follower-count "${FOLLOWER_COUNT}"
-  ./bin/test-appliance-follower-logs-for-replication-slot-errors --log-directory "$LOG_DIR/logs/follower"
+  # Run all test suite commands and capture their exit codes. Any failure
+  # does not prevent the following tests from running.
+  set +e
+  announce "BEGIN TEST SUITE - BEFORE FAILOVER"
+  for i in "${!TEST_COMMANDS[@]}"; do
+    announce "BEGIN TEST: ${TEST_COMMANDS[$i]}"
+    # shellcheck disable=SC2086
+    eval ${TEST_COMMANDS[$i]}
+    # shellcheck disable=SC2004
+    EXIT_CODES_FIRST_RUN[$i]=$?
+  done
 
   echo "Triggering a Leader failover..."
   perform_failover
@@ -138,17 +161,14 @@ main(){
   echo "Waiting for Follower(s) to become healthy after rebasing..."
   wait_for_followers
 
-  echo "Gathering test results again..."
-  ./bin/test-follower-pg-identifier --follower-count "${FOLLOWER_COUNT}"
-  ./bin/dump-appliance-health-and-info --follower-count "${FOLLOWER_COUNT}"
-  ./bin/test-secret-replication --max-attempts "${MAX_ATTEMPTS}" --policy-count "${POLICY_COUNT}" --secret-count "${SECRET_COUNT}" --follower-count "${FOLLOWER_COUNT}"
-  ./bin/test-table-rows-match --follower-count "${FOLLOWER_COUNT}" --max-attempts "${MAX_ATTEMPTS}"
-
-  # These the test below depends on the appliance logs...
-  ./bin/dump-leader-logs --log-directory "$LOG_DIR/logs/leader"
-  ./bin/dump-appliance-follower-logs --log-directory "$LOG_DIR/logs/follower" --follower-count "${FOLLOWER_COUNT}"
-  ./bin/test-leader-logs-for-replication-slot-errors --log-directory "$LOG_DIR/logs/leader"
-  ./bin/test-appliance-follower-logs-for-replication-slot-errors --log-directory "$LOG_DIR/logs/follower"
+  announce "BEGIN TEST SUITE - AFTER FAILOVER"
+  for i in "${!TEST_COMMANDS[@]}"; do
+    announce "BEGIN TEST: ${TEST_COMMANDS[$i]}"
+    # shellcheck disable=SC2086
+    eval ${TEST_COMMANDS[$i]}
+    # shellcheck disable=SC2004
+    EXIT_CODES_SECOND_RUN[$i]=$?
+  done
 
   echo "Tests are finished executing!"
   echo "DONE."
@@ -211,6 +231,11 @@ deploy_followers() {
 }
 
 perform_failover() {
+  if [ "$USE_EXISTING_ENVIRONMENT" = "true" ]; then
+    echo "USE_EXISTING_ENVIRONMENT is set to '$USE_EXISTING_ENVIRONMENT', skipping triggering auto-failover..."
+    return
+  fi
+
   # Trigger a failover and wait for the cluster to become healthy again
   bin/dap --trigger-failover
   sleep 5
@@ -259,13 +284,15 @@ wait_for_follower() {
 # IMPORTANT: this is all done in sequence, each statistic is not a separate
 # process!
 record_resource_utilization() {
+  # Suppress output from stdout
+  set +x
   while true; do
-    snapshot_top
-    snapshot_docker_stats
-    snapshot_leader_replication_status
-    snapshot_follower_replication_status
-    snapshot_leader_pg_identifier
-    snapshot_follower_pg_identifier
+    snapshot_top > /dev/null 2>&1
+    snapshot_docker_stats > /dev/null 2>&1
+    snapshot_leader_replication_status > /dev/null 2>&1
+    snapshot_follower_replication_status > /dev/null 2>&1
+    snapshot_leader_pg_identifier > /dev/null 2>&1
+    snapshot_follower_pg_identifier > /dev/null 2>&1
     sleep "$RESOURCE_INTERVAL"
   done
 }
@@ -416,6 +443,39 @@ xtop() {
       # Linux
       top -b -n 1 | head -n 30
   fi
+}
+
+print_test_suite_summary() {
+  announce "TEST SUITE SUMMARY"
+  
+  for i in "${!TEST_COMMANDS[@]}"; do
+    echo "Command: ${TEST_COMMANDS[$i]}"
+    echo "Exit code before failover: ${EXIT_CODES_FIRST_RUN[$i]}"
+    echo "Exit code after failover: ${EXIT_CODES_SECOND_RUN[$i]}"
+  done
+}
+
+determine_exit_code() {
+  if [ "$1" -ne 0 ]; then
+    echo "Setup failed with exit code: $exit_code"
+    return 1
+  fi
+
+  for exit_code in "${EXIT_CODES_FIRST_RUN[@]}"; do
+    if [ "$exit_code" -ne 0 ]; then
+      echo "A test failed with exit code: $exit_code"
+      return 1
+    fi
+  done
+
+  for exit_code in "${EXIT_CODES_SECOND_RUN[@]}"; do
+    if [ "$exit_code" -ne 0 ]; then
+      echo "A test failed with exit code: $exit_code"
+      return 1
+    fi
+  done
+
+  return 0
 }
 
 main "$@"
