Trigger a failover and ensure Follower health

diff --git a/bin/replication-test b/bin/replication-test
--- a/bin/replication-test
+++ b/bin/replication-test
@@ -113,6 +113,7 @@ main(){
   fi
 
   # Begin test suite
+  echo "Gathering test results..."
   ./bin/test-follower-pg-identifier --follower-count "${FOLLOWER_COUNT}"
   ./bin/dump-appliance-health-and-info --follower-count "${FOLLOWER_COUNT}"
   ./bin/test-table-rows-match --follower-count "${FOLLOWER_COUNT}" --max-attempts "${MAX_ATTEMPTS}"
@@ -120,6 +121,16 @@ main(){
   # These the test below depends on the appliance logs...
   ./bin/dump-appliance-logs --follower-count "${FOLLOWER_COUNT}"
   ./bin/test-appliance-logs-for-replication-slot-errors
+
+  echo "Triggering a Leader failover..."
+  perform_failover
+
+  # Wait 5 minutes for all Followers to begin rebasing
+  echo "Waiting 5 minutes for Follower(s) to begin rebasing..."
+  sleep 300
+
+  echo "Waiting for Follower(s) to become healthy after rebasing..."
+  wait_for_followers
 
   echo "Tests are finished executing!"
   echo "DONE."
@@ -143,15 +154,11 @@ deploy_and_restore_leader() {
   bin/dap --provision-master --version "$VERSION"
 
   # The most recent backup is used from system/backup
-  echo "Restoring the Leader from backup using tag: '${VERSION}'..."
-  bin/dap --restore-from-backup --version "$VERSION"
-
-  echo "Importing certificates..."
-  bin/dap --import-custom-certificates
+  # echo "Restoring the Leader from backup using tag: '${VERSION}'..."
+  # bin/dap --restore-from-backup --version "$VERSION"
 
   echo "Deploying the Standbys..."
   bin/dap --provision-standbys --version "$VERSION"
-
   bin/dap --wait-for-master
 
   echo "Enabling auto-failover..."
@@ -179,6 +186,52 @@ deploy_followers() {
       echo "FATAL: Failed to configure Follower(s) with error: $exit_status"
       exit 1
   fi
+}
+
+perform_failover() {
+  # Trigger a failover and wait for the cluster to become healthy again
+  bin/dap --trigger-failover
+  sleep 5
+  bin/dap --wait-for-master
+}
+
+wait_for_followers() {
+  for ((i=1; i<=FOLLOWER_COUNT; i++))
+  do
+    echo "Waiting for Follower conjur-follower-${i}.mycompany.local to be healthy..."
+    wait_for_follower "conjur-follower-${i}.mycompany.local"
+  done
+}
+
+wait_for_follower() {
+  local follower_hostname=$1
+  local container_id
+  local attempts=0
+  local max_attempts=180
+
+  container_id=$(docker compose ps -q $follower_hostname)
+  if [ -z "$container_id" ]; then
+    echo "WARNING: No container ID found for service '$follower_hostname' (it is not running), skipping!"
+    return
+  fi
+
+  while true; do
+    attempts=$((attempts + 1))
+    if [ $attempts -gt $max_attempts ]; then
+      echo "FATAL: Follower '$follower_hostname' did not become healthy after '$max_attempts' attempts!"
+      exit 1
+    fi
+
+    echo "Checking Follower '$follower_hostname' health status (attempt $attempts/$max_attempts)..."
+    if docker compose exec "$follower_hostname" curl -k --fail-with-body https://localhost/health &>/dev/null; then
+      echo "Follower '$follower_hostname' is healthy!"
+      break
+    fi
+
+    echo "Follower '$follower_hostname' is not healthy yet, waiting 10 seconds before trying again..."
+    sleep 10
+  done
+
 }
 
 # IMPORTANT: this is all done in sequence, each statistic is not a separate
