Add replication-test-k8s
- Centralize root log directory for replication tests
- Add dumping of k8s resources to `create-log-artifacts`
- Note: each replication test driver outputs logs to its own directory, however both replication tests share the same parent directory. Each test driver script will destroy their respective log directories (not the parent directory) per run
- A variable number of K8S Followers can be deployed and tested with this script
- Previously, if only one of the replication test stages were enabled via params, both would still run. This seems to be due to how jenkins resolves empty (non-null) strings to a truthy value
- Includes a separate jenkins parameter for REPLICATION_K8S_FOLLOWER_COUNT
- We discovered that there are resource constraints in KinD in CI, where the KinD cluster appears to not be using as much compute as we'd like, which seems to limit how quickly K8S Followers can rollout
- K8S Followers currently have a hardcode health readiness check, if not met, causes them to be restarted
- Therefore, it is important that if we run replication tests against Appliance Followers and K8S Followers in one job, that FOLLOWER_COUNT field for each of them is individually configurable

diff --git a/bin/replication-test-k8s b/bin/replication-test-k8s
--- a/bin/replication-test-k8s
+++ b/bin/replication-test-k8s
@@ -5,16 +5,21 @@ set -ex
 
 # USAGE
 #
-# This restores a Leader from backup, deploys and configures a number of
+# This restores a Leader from backup, deploys and configures a number of K8S
 # Followers, and runs a series of tests to verify that replication is working
 # as expected. It also monitors the host for system resource utilization,
 # the container logs, and outputs them into a single tarball.
 #
-# VERSION=5.0-stable FOLLOWER_COUNT=2 ./bin/replication-test
-# VERSION=13.3.0 FOLLOWER_COUNT=2 ./bin/replication-test
+# ./bin/replication-test-k8s
+#
+# Patch release: 13.3.2
+# VERSION=5.17.4-12 K8S_FOLLOWER_TAG=2.3.5-10 FOLLOWER_COUNT=2 ./bin/replication-test-k8s
+#
+# Production release: 13.3.0
+# VERSION=13.3.0 K8S_FOLLOWER_TAG=2.3.4-6 FOLLOWER_COUNT=2 ./bin/replication-test-k8s
 #
 # Useful for when only testing changes to tests or the test harness itself:
-# USE_EXISTING_ENVIRONMENT=true ./bin/replication-test
+# USE_EXISTING_ENVIRONMENT=true ./bin/replication-test-k8s
 #
 
 # Always work from repo root directory
@@ -23,7 +28,7 @@ cd "$(dirname ${0})/..";
 source ./bin/functions
 source ./bin/utils.sh
 
-LOG_DIR="$(replication_test_log_dir)/replication-test"
+LOG_DIR="$(replication_test_log_dir)/replication-test-k8s"
 RESOURCE_UTLIZATION_LOG_DIR="$LOG_DIR/resources"
 TOP_LOG_DIR="$RESOURCE_UTLIZATION_LOG_DIR/top"
 DOCKER_STATS_LOG_DIR="$RESOURCE_UTLIZATION_LOG_DIR/docker_stats"
@@ -33,9 +38,9 @@ ARCHIVE_DIR="tmp/artifacts"
 DOCKER_LEADER_CONTAINER="conjur-master-1.mycompany.local"
 
 USE_EXISTING_ENVIRONMENT="${USE_EXISTING_ENVIRONMENT:-false}"
+K8S_FOLLOWER_TAG="${K8S_FOLLOWER_TAG:-edge}"
 VERSION="${VERSION:-5.0-stable}"
 FOLLOWER_COUNT="${FOLLOWER_COUNT:-2}"
-LEADER_COUNT="${LEADER_COUNT:-3}"
 RESOURCE_INTERVAL="${RESOURCE_INTERVAL:-60}"
 MAX_ATTEMPTS="${MAX_ATTEMPTS:-10}"
 # The timeout in seconds to wait for the all Followers to be deployed
@@ -43,7 +48,7 @@ MAX_ATTEMPTS="${MAX_ATTEMPTS:-10}"
 CONFIGURE_FOLLOWER_TIMEOUT=${CONFIGURE_FOLLOWER_TIMEOUT:-600}
 
 # Use this to hide WARN from docker compose...
-# WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
+# WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string. 
 export VERSION
 
 pid=""
@@ -72,7 +77,7 @@ main(){
     exit 1
   fi
 
-  echo "Running replication tests with '${FOLLOWER_COUNT}' Follower(s) on Appliance Version '${VERSION}'..."
+  echo "Running replication tests with '${FOLLOWER_COUNT}' K8S Follower(s) on with Leader Appliance Version '${VERSION}'..."
 
   echo "Removing old logs from: $LOG_DIR"
   rm -rf "$LOG_DIR"
@@ -97,13 +102,13 @@ main(){
   record_resource_utilization &
   pid=$!
   echo "Starting resource monitor: $pid"
-  echo "Provisioning Follower(s) using tag: '${VERSION}'..."
+  echo "Provisioning K8S Follower(s) using tag: '${K8S_FOLLOWER_TAG}'..."
   echo "If any one Follower takes longer than $CONFIGURE_FOLLOWER_TIMEOUT seconds to configure, the configuration process for all Followers will be stopped."
 
   # The following enables us to kill long-running configurations (hanging).
   # This allows the pipeline to continue, fail, and for artifacts to still be
   # generated.
-  deploy_followers
+  deploy_k8s_followers
 
   # This is a Developer Exprience option for using USE_EXISTING_ENVIRONMENT
   if [ "$USE_EXISTING_ENVIRONMENT" = "true" ]; then
@@ -116,33 +121,9 @@ main(){
   fi
 
   # Begin test suite
-  echo "Gathering test results..."
-  ./bin/test-follower-pg-identifier --follower-count "${FOLLOWER_COUNT}"
-  ./bin/dump-appliance-health-and-info --follower-count "${FOLLOWER_COUNT}"
-  ./bin/test-table-rows-match --follower-count "${FOLLOWER_COUNT}" --max-attempts "${MAX_ATTEMPTS}"
-
-  # These the test below depends on the appliance logs...
-  ./bin/dump-appliance-logs --follower-count "${FOLLOWER_COUNT}"
-  ./bin/test-appliance-logs-for-replication-slot-errors
-
-  echo "Triggering a Leader failover..."
-  perform_failover
-
-  # Wait 5 minutes for all Followers to begin rebasing
-  echo "Waiting 5 minutes for Follower(s) to begin rebasing..."
-  sleep 300
-
-  echo "Waiting for Follower(s) to become healthy after rebasing..."
-  wait_for_followers
-
-  echo "Gathering test results again..."
-  ./bin/test-follower-pg-identifier --follower-count "${FOLLOWER_COUNT}"
-  ./bin/dump-appliance-health-and-info --follower-count "${FOLLOWER_COUNT}"
-  ./bin/test-table-rows-match --follower-count "${FOLLOWER_COUNT}" --max-attempts "${MAX_ATTEMPTS}"
-
-  # These the test below depends on the appliance logs...
-  ./bin/dump-appliance-logs --follower-count "${FOLLOWER_COUNT}"
-  ./bin/test-appliance-logs-for-replication-slot-errors
+  # ./bin/test-follower-pg-identifier --follower-count "${FOLLOWER_COUNT}"
+  # ./bin/dump-appliance-health-and-info --follower-count "${FOLLOWER_COUNT}"
+  # ./bin/test-table-rows-match --follower-count "${FOLLOWER_COUNT}" --max-attempts "${MAX_ATTEMPTS}"
 
   echo "Tests are finished executing!"
   echo "DONE."
@@ -168,98 +149,37 @@ deploy_and_restore_leader() {
   # The most recent backup is used from system/backup
   echo "Restoring the Leader from backup using tag: '${VERSION}'..."
   bin/dap --restore-from-backup --version "$VERSION"
-
-  echo "Importing certificates..."
-  bin/dap --import-custom-certificates --version "$VERSION"
-  bin/dap --wait-for-master
-
-  echo "Deploying the Standbys..."
-  bin/dap --provision-standbys --version "$VERSION"
-  bin/dap --wait-for-master
-
-  echo "Enabling auto-failover..."
-  bin/dap --enable-auto-failover --auto-failover-ttl 60
-
-  echo "Waiting for healthy cluster..."
-  bin/dap --wait-for-master
 }
 
-deploy_followers() {
+deploy_k8s_followers() {
   if [ "$USE_EXISTING_ENVIRONMENT" = "true" ]; then
     echo "USE_EXISTING_ENVIRONMENT is set to '$USE_EXISTING_ENVIRONMENT', skipping deployment of Followers..."
     return
   fi
 
-  set +e
-  { timeout "$CONFIGURE_FOLLOWER_TIMEOUT" ./bin/dap --provision-follower --version "${VERSION}" --follower-count "${FOLLOWER_COUNT}"; exit_status=$?; }
-  set -e
-  if [ $exit_status -eq 124 ]; then
-    echo "FATAL: Timeout of '$CONFIGURE_FOLLOWER_TIMEOUT' exceeded when provisioning Follower(s)!"
-    exit 1
-  elif [ $exit_status -eq 0 ]; then
-      echo "SUCCESS: Follower(s) were succesfully configured completed before timeout!"
+  ./bin/dap --provision-k8s-follower --k8s-follower-version "${K8S_FOLLOWER_TAG}" --follower-count "${FOLLOWER_COUNT}" --k8s-follower-conjur-log-level debug
+  exit_status="$?"
+
+  if [ $exit_status -eq 0 ]; then
+    echo "SUCCESS: K8S Follower(s) were succesfully configured completed before timeout!"
   else
-      echo "FATAL: Failed to configure Follower(s) with error: $exit_status"
-      exit 1
+    echo "FATAL: Failed to configure K8S Follower(s) with error: $exit_status"
+    exit 1
   fi
-}
-
-perform_failover() {
-  # Trigger a failover and wait for the cluster to become healthy again
-  bin/dap --trigger-failover
-  sleep 5
-  bin/dap --wait-for-master
-}
-
-wait_for_followers() {
-  for ((i=1; i<=FOLLOWER_COUNT; i++))
-  do
-    echo "Waiting for Follower conjur-follower-${i}.mycompany.local to be healthy..."
-    wait_for_follower "conjur-follower-${i}.mycompany.local"
-  done
-}
-
-wait_for_follower() {
-  local follower_hostname=$1
-  local container_id
-  local attempts=0
-  local max_attempts=180
-
-  container_id=$(docker compose ps -q $follower_hostname)
-  if [ -z "$container_id" ]; then
-    echo "WARNING: No container ID found for service '$follower_hostname' (it is not running), skipping!"
-    return
-  fi
-
-  while true; do
-    attempts=$((attempts + 1))
-    if [ $attempts -gt $max_attempts ]; then
-      echo "FATAL: Follower '$follower_hostname' did not become healthy after '$max_attempts' attempts!"
-      exit 1
-    fi
-
-    echo "Checking Follower '$follower_hostname' health status (attempt $attempts/$max_attempts)..."
-    if docker compose exec "$follower_hostname" curl -k --fail-with-body https://localhost/health &>/dev/null; then
-      echo "Follower '$follower_hostname' is healthy!"
-      break
-    fi
-
-    echo "Follower '$follower_hostname' is not healthy yet, waiting 10 seconds before trying again..."
-    sleep 10
-  done
-
 }
 
 # IMPORTANT: this is all done in sequence, each statistic is not a separate
 # process!
 record_resource_utilization() {
+  # Suppress output from stdout
+  set +x
   while true; do
-    snapshot_top
-    snapshot_docker_stats
-    snapshot_leader_replication_status
-    snapshot_follower_replication_status
-    snapshot_leader_pg_identifier
-    snapshot_follower_pg_identifier
+    snapshot_top > /dev/null 2>&1
+    snapshot_docker_stats > /dev/null 2>&1
+    snapshot_leader_replication_status > /dev/null 2>&1
+    # snapshot_follower_replication_status > /dev/null 2>&1
+    snapshot_leader_pg_identifier > /dev/null 2>&1
+    # snapshot_follower_pg_identifier > /dev/null 2>&1
     sleep "$RESOURCE_INTERVAL"
   done
 }
@@ -279,36 +199,24 @@ snapshot_leader_replication_status() {
   local log_dir
 
   timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S.000+00:00")
+  log_dir="$REPLICATION_LOG_STATS_DIR/leader/$DOCKER_LEADER_CONTAINER"
+  pg_stat_replication_log_dir="$log_dir/pg_stat_replication"
+  pg_stat_replication_log_dir_log_file="$pg_stat_replication_log_dir/$timestamp.log"
+  pg_stat_activity_log_dir="$log_dir/pg_stat_activity"
+  pg_stat_activity_log_dir_log_file="$pg_stat_activity_log_dir/$timestamp.log"
 
-  # Collect the replication status from each leader container
-  for ((i=1; i<=LEADER_COUNT; i++)); do
-    local leader_container="conjur-master-${i}.mycompany.local"
+  mkdir -p "$pg_stat_replication_log_dir"
+  mkdir -p "$pg_stat_activity_log_dir"
 
-    container_id=$(docker compose ps -q $leader_container)
-    if [ -z "$container_id" ]; then
-      echo "WARNING: No container ID found for service '$leader_container' (it is not running), skipping!"
-      continue
-    fi
+  docker compose exec -T "$DOCKER_LEADER_CONTAINER" bash -c $"
+        chpst -u conjur psql -c \"\\copy (SELECT * from pg_stat_replication) To '/tmp/output.csv' With CSV HEADER\"
+      " || true
+  docker compose exec "$DOCKER_LEADER_CONTAINER" bash -c "cat /tmp/output.csv" | tee "$pg_stat_replication_log_dir_log_file" || true
 
-    log_dir="$REPLICATION_LOG_STATS_DIR/leader/$leader_container"
-    pg_stat_replication_log_dir="$log_dir/pg_stat_replication"
-    pg_stat_replication_log_dir_log_file="$pg_stat_replication_log_dir/$timestamp.log"
-    pg_stat_activity_log_dir="$log_dir/pg_stat_activity"
-    pg_stat_activity_log_dir_log_file="$pg_stat_activity_log_dir/$timestamp.log"
-
-    mkdir -p "$pg_stat_replication_log_dir"
-    mkdir -p "$pg_stat_activity_log_dir"
-
-    docker compose exec -T "$leader_container" bash -c $"
-          chpst -u conjur psql -c \"\\copy (SELECT * from pg_stat_replication) To '/tmp/output.csv' With CSV HEADER\"
-        " || true
-    docker compose exec "$leader_container" bash -c "cat /tmp/output.csv" | tee "$pg_stat_replication_log_dir_log_file" || true
-
-    docker compose exec -T "$leader_container" bash -c $"
-          chpst -u conjur psql -c \"\\copy (SELECT * from pg_stat_activity) To '/tmp/output.csv' With CSV HEADER\"
-        " || true
-    docker compose exec "$leader_container" bash -c "cat /tmp/output.csv" | tee "$pg_stat_activity_log_dir_log_file" || true
-  done
+  docker compose exec -T "$DOCKER_LEADER_CONTAINER" bash -c $"
+        chpst -u conjur psql -c \"\\copy (SELECT * from pg_stat_activity) To '/tmp/output.csv' With CSV HEADER\"
+      " || true
+  docker compose exec "$DOCKER_LEADER_CONTAINER" bash -c "cat /tmp/output.csv" | tee "$pg_stat_activity_log_dir_log_file" || true
 }
 
 # Print information of the replication status of each Follower
@@ -355,25 +263,13 @@ snapshot_leader_pg_identifier() {
   local log_dir
 
   timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S.000+00:00")
+  log_dir="$PG_ID_LOG_DIR/leader/$DOCKER_LEADER_CONTAINER"
 
-  # Collect the identifier from each leader container
-  for ((i=1; i<=LEADER_COUNT; i++)); do
-    local leader_container="conjur-master-${i}.mycompany.local"
+  mkdir -p "$log_dir"
 
-    container_id=$(docker compose ps -q $leader_container)
-    if [ -z "$container_id" ]; then
-      echo "WARNING: No container ID found for service '$leader_container' (it is not running), skipping!"
-      continue
-    fi
-
-    log_dir="$PG_ID_LOG_DIR/leader/$leader_container"
-
-    mkdir -p "$log_dir"
-
-    pgid=$(docker compose exec -T "$leader_container" chpst -u postgres psql -tqc 'SELECT system_identifier FROM pg_control_system();')
-    echo "Got pg identifer for Leader '$leader_container': $pgid"
-    echo "$pgid" > "$log_dir/$timestamp.log" || true
-  done
+  pgid=$(docker compose exec -T "$DOCKER_LEADER_CONTAINER" chpst -u postgres psql -tqc 'SELECT system_identifier FROM pg_control_system();')
+  echo "Got pg identifer for Leader '$DOCKER_LEADER_CONTAINER': $pgid"
+  echo "$pgid" > "$log_dir/$timestamp.log" || true
 }
 
 snapshot_follower_pg_identifier() {
