Add timeout to kill Followers that take too long to configure
- This enables the pipeline to fail gracefully (without having to aborting an infinite loop) in the case that the configuration of a Follower remains in an infinite loop
- e.g.) `Waiting for initial table sync to complete...`

diff --git a/bin/replication-test b/bin/replication-test
--- a/bin/replication-test
+++ b/bin/replication-test
@@ -30,6 +30,9 @@ VERSION="${VERSION:-'5.0-stable'}"
 FOLLOWER_COUNT="${FOLLOWER_COUNT:-2}"
 RESOURCE_INTERVAL="${RESOURCE_INTERVAL:-60}"
 MAX_ATTEMPTS="${MAX_ATTEMPTS:-10}"
+# The timeout in seconds to wait for the all Followers to be deployed
+# 10 Minute Default
+CONFIGURE_FOLLOWER_TIMEOUT=${CONFIGURE_FOLLOWER_TIMEOUT:-600}
 
 # Use this to hide WARN from docker compose...
 # WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string. 
@@ -50,6 +53,11 @@ finish() {
 
 main(){
   trap finish EXIT
+
+  if ! command -v timeout >/dev/null 2>&1; then
+    echo "FATAL: the timeout command is not available which is a requirement for this script."
+    exit 1
+  fi
 
   echo "Running replication tests with '${FOLLOWER_COUNT}' Follower(s) on Appliance Version '${VERSION}'..."
 
@@ -81,7 +89,23 @@ main(){
   echo "Starting resource monitor: $pid"
 
   echo "Provisioning Follower(s) using tag: '${VERSION}'..."
-  ./bin/dap --provision-follower --version "${VERSION}" --follower-count "${FOLLOWER_COUNT}"
+  echo "If any one Follower takes longer than $CONFIGURE_FOLLOWER_TIMEOUT seconds to configure, the configuration process for all Followers will be stopped."
+
+  # The following enables us to kill long-running configurations (hanging).
+  # This allows the pipeline to continue, fail, and for artifacts to still be
+  # generated.
+  set +e
+  { timeout "$CONFIGURE_FOLLOWER_TIMEOUT" ./bin/dap --provision-follower --version "${VERSION}" --follower-count "${FOLLOWER_COUNT}"; exit_status=$?; }
+  set -e
+  if [ $exit_status -eq 124 ]; then
+    echo "FATAL: Timeout of '$CONFIGURE_FOLLOWER_TIMEOUT' exceeded when provisioning Follower(s)!"
+    exit 1
+  elif [ $exit_status -eq 0 ]; then
+      echo "SUCCESS: Follower(s) were succesfully configured completed before timeout!"
+  else
+      echo "FATAL: Failed to configure Follower(s) with error: $exit_status"
+      exit 1
+  fi
 
   ./bin/test-follower-pg-identifier --follower-count "${FOLLOWER_COUNT}"
   ./bin/dump-appliance-health-and-info --follower-count "${FOLLOWER_COUNT}"
