Re-introduce test-secret-replication
- This script has been re-added to the Appliance Follower `replication-test` which will allow the Automatic Failover test (in a separate PR) to be more accurately tested
- Abstract out the creation of policy, and setting of secrets. This enables the callers of these scripts to have more control over flow control
- Add test-secret-replication-k8s
  - Adds the equivalent secrets replication test to the K8S Followers
  - This test should is done before the table rows are compared to the Leader

diff --git a/bin/test-secret-replication-k8s b/bin/test-secret-replication-k8s
--- a/bin/test-secret-replication-k8s
+++ b/bin/test-secret-replication-k8s
@@ -6,39 +6,23 @@
 #
 # 1) Load a dynamic policy with a secret into the Leader
 # 2) Set the secret on the Leader
-# 3) Verify that the secret is replicated to each Appliance Follower (parallel)
-#
-# If a secret did not replicate within the --max-attempts, the script will
-# fail.
+# 3) Verify that the secret is replicated to each K8S Follower (parallel)
 #
 # When verifying secrets on the K8S Followers, the script will attempt to
 # authenticate with the Follower to retrieve an access token.
 #
+# If a secret did not replicate within the --max-attempts, the script will
+# fail.
+#
 # IMPORTANT: the $BASE_POLICY_BRANCH is reset per run of this script. It will
 # remain after the script is run. This is intentional so that
-# `test-table-rows-match` has data to work with.
+# `test-table-rows-match-k8s` has data to work with.
 #
 # USAGE
-# ./bin/test-secret-replication --max-attempts 10 --policy-count 2 --secret-count 2 --follower-count 2
+# ./bin/test-secret-replication-k8s --max-attempts 10 --policy-count 2 --secret-count 2 --follower-count 2
 #
-# This test has been encountering issues where:
-#
-# 1) A Token provided by a Leader is seen as invalid, but the token
-# works for other Followers. This is seen in the Follower log:
-#
-# conjur-follower-3.mycompany.local-1  | <14>1 2024-06-04T22:37:02.000+00:00 ffe6d49725ac conjur-possum 1058 - [meta sequenceId="39"] [origin=12.16.23.11] [request_id=bc42f74e-3da1-478e-b47d-b103b7745f33] [tid=1070] Started GET "/secrets/demo/variable/replication-test%2Fpolicy-1%2Fsecret_1" for 12.16.23.11 at 2024-06-04 22:37:02 +0000
-# conjur-follower-3.mycompany.local-1  | <13>1 2024-06-04T22:37:03.622+00:00 ffe6d49725ac nginx - - [meta sequenceId="40"] 12.16.23.11 "-" "GET /secrets/demo/variable/replication-test%2Fpolicy-1%2Fsecret_1 HTTP/1.1" 401 27 "-" "curl/7.81.0" 0.028 0.028
-#
-# 2) A token provided by a Follower is seen as invalid. This is seen
-# in the Follower log:
-#
-# conjur-follower-2.mycompany.local-1  | <14>1 2024-06-04T22:57:32.000+00:00 9abb871007d8 conjur-possum 1071 - [meta sequenceId="171"] [origin=12.16.23.11] [request_id=174d748f-60f7-493e-802f-b2de7aaf16c3] [tid=1094] Started GET "/authn/demo/login" for 12.16.23.11 at 2024-06-04 22:57:32 +0000
-# conjur-follower-2.mycompany.local-1  | <14>1 2024-06-04T22:57:32.000+00:00 9abb871007d8 conjur-possum 1071 - [meta sequenceId="172"] [origin=12.16.23.11] [request_id=174d748f-60f7-493e-802f-b2de7aaf16c3] [tid=1094] Processing by AuthenticateController#login as */*
-# conjur-follower-2.mycompany.local-1  | <14>1 2024-06-04T22:57:32.000+00:00 9abb871007d8 conjur-possum 1071 - [meta sequenceId="173"] [origin=12.16.23.11] [request_id=174d748f-60f7-493e-802f-b2de7aaf16c3] [tid=1094]   Parameters: {:controller=>"authenticate", :action=>"login", :authenticator=>"authn", :account=>"demo"}
-# conjur-follower-2.mycompany.local-1  | <14>1 2024-06-04T22:57:32.000+00:00 9abb871007d8 conjur-possum 1071 - [meta sequenceId="174"] [origin=12.16.23.11] [request_id=174d748f-60f7-493e-802f-b2de7aaf16c3] [tid=1094] CONJ00047I Login Error: #<Errors::Authentication::Security::AccountNotDefined: CONJ00008E Account 'demo' is not defined in Conjur>
-#
-# This seems to indicate that a Follower might be in the process of
-# replicating (healthily) still... so increase MAX_ATTEMPTS reasonably.
+# This test can encounter similar issues with Follower Authentication as
+# described in the `test-secret-replication` script.`
 #
 
 # Always work from repo root directory
@@ -48,6 +32,8 @@ source ./bin/functions
 source ./bin/utils.sh
 
 DOCKER_LEADER_CONTAINER="conjur-master-1.mycompany.local"
+# All Followers will query themselves for authentication/secrets
+FOLLOWER_HOSTNAME="localhost:8080"
 CONJUR_USER="admin"
 CONJUR_ACCOUNT="demo"
 CONJUR_PASSWORD="MySecretP@ss1"
@@ -59,9 +45,8 @@ MAX_ATTEMPTS=
 export VERSION=
 FOLLOWER_LOAD_SECRET_JOB_PIDS=()
 
-POLICY_COUNT=
-SECRET_COUNT=
 FOLLOWER_COUNT=
+SECRET_COUNT=
 
 cleanup_background_jobs() {
   # NOTE: this will only stop the background jobs for configuring a Follower
@@ -159,14 +144,21 @@ set_secrets(){
 }
 
 verify_secrets_on_followers() {
-  echo "Begin testing Appliance Follower replciation for secret '$secret_id' with value '$secret_value'..."
-  for ((j=1; j<=FOLLOWER_COUNT; j++))
-  do
-    # Execute the following in parallel...
-    local follower_hostname
+  echo "Begin testing K8S Follower replciation for secret '$secret_id' with value '$secret_value'..."
 
-    follower_hostname="conjur-follower-${j}.mycompany.local"
-    echo "[$follower_hostname] Starting job to get secret from follower $follower_hostname..."
+  RUNNING_PODS=$(get_k8s_follower_pod_names)
+  echo "$RUNNING_PODS"
+
+  RUNNING_PODS_COUNT=$(echo "$RUNNING_PODS" | wc -w | tr -d ' ')
+
+  if [ "$RUNNING_PODS_COUNT" -ne "$FOLLOWER_COUNT" ]; then
+    echo "FATAL: The number of running pods '$RUNNING_PODS_COUNT' is not equal to the expected FOLLOWER_COUNT: '${FOLLOWER_COUNT}'. Exiting..."
+    exit 1
+  fi
+
+  for pod in $RUNNING_PODS; do
+    # Execute the following in parallel...
+    echo "[$pod] Starting job to get secret from follower $pod..."
 
     # This is a job...
     (
@@ -175,32 +167,40 @@ verify_secrets_on_followers() {
         local token_from_follower
         local value_on_follower
 
-        echo "[$follower_hostname] (Attempt: $k/$MAX_ATTEMPTS) - Begin checking secret '$secret_id' on follower '$follower_hostname'..."
+        echo "[$pod] (Attempt: $k/$MAX_ATTEMPTS) - Begin checking secret '$secret_id' on follower '$pod'..."
 
-        token_from_follower=$(get_conjur_access_token_from_follower "$follower_hostname")
-        value_on_follower=$(get_secret_from_follower "$follower_hostname" "$secret_id" "$token_from_follower")
+        token_from_follower=$(get_conjur_access_token_from_follower "$pod")
+        if [[ -z "$token_from_follower" ]]; then
+          echo "[$pod] FATAL: Failed to get Conjur Access Token from follower! Retrying..."
+          sleep 3
+          continue
+        fi
 
-        echo "[$follower_hostname] [DEBUG] Recieved value from follower: $value_on_follower"
+        echo "[$pod] [DEBUG] Recieved token_from_follower from follower: $token_from_follower"
+
+        value_on_follower=$(get_secret_from_follower "$pod" "$secret_id" "$token_from_follower")
+        echo "[$pod] [DEBUG] Recieved value from follower: $value_on_follower"
+        # value_on_follower="qwe"
 
         # Test the value received from the Follower
         if [[ "$value_on_follower" == "Malformed authorization token" ]]; then
           # If this occurs, it is likely a developer error
-          echo "[$follower_hostname] (Attempt: $k/$MAX_ATTEMPTS) - FATAL: the token used to authenticate with the Follower is invalid -- disregarding MAX_ATTEMPTS and exiting..."
+          echo "[$pod] (Attempt: $k/$MAX_ATTEMPTS) - FATAL: the token used to authenticate with the Follower is invalid -- disregarding MAX_ATTEMPTS and exiting..."
           exit 1
         elif [[ "$value_on_follower" == "$secret_value" ]]; then
-          echo "[$follower_hostname] (Attempt: $k/$MAX_ATTEMPTS) - Successfully replicated secret '$secret_id' with value '$value_on_follower' to follower '$follower_hostname'."
+          echo "[$pod] (Attempt: $k/$MAX_ATTEMPTS) - Successfully replicated secret '$secret_id' with value '$value_on_follower' to follower '$pod'."
           break
         elif [[ "$k" -eq $MAX_ATTEMPTS ]]; then
-          echo "[$follower_hostname] (Attempt: $k/$MAX_ATTEMPTS) - FATAL: Follower $follower_hostname failed to replicate '$secret_id'. Expected '$secret_id' to be '$secret_value', got '$value_on_follower'..."
+          echo "[$pod] (Attempt: $k/$MAX_ATTEMPTS) - FATAL: Follower $pod failed to replicate '$secret_id'. Expected '$secret_id' to be '$secret_value', got '$value_on_follower'..."
 
           # Make visible the situation documented above
           if [[ "$value_on_follower" == "Unauthorized: Invalid token" ]]; then
-            echo "[$follower_hostname] (Attempt: $k/$MAX_ATTEMPTS) - WARNING: it seems like the Follower is still replicating, and the resources associated with this token are not yet available. This might be a transient issue that can be resolved by increasing 'MAX_ATTEMPTS', or the Follower might be unhealthy."
+            echo "[$pod] (Attempt: $k/$MAX_ATTEMPTS) - WARNING: it seems like the Follower is still replicating, and the resources associated with this token are not yet available. This might be a transient issue that can be resolved by increasing 'MAX_ATTEMPTS', or the Follower might be unhealthy."
           fi
           exit 1
         fi
 
-        echo "[$follower_hostname] (Attempt: $k/$MAX_ATTEMPTS) - Retrying in 3 seconds..."
+        echo "[$pod] (Attempt: $k/$MAX_ATTEMPTS) - Retrying in 3 seconds..."
         sleep 3
       done
     ) &
@@ -228,6 +228,9 @@ verify_secrets_on_followers() {
     fi
     sleep 1
   done
+
+  # Reset global for the next iteration
+  FOLLOWER_LOAD_SECRET_JOB_PIDS=()
 }
 
 # Conjur Access Tokens work across all Leaders/Followers. Let's get a token
@@ -244,30 +247,37 @@ get_conjur_access_token() {
 }
 
 get_conjur_access_token_from_follower() {
-  TARGET_HOST="$1"
-  API_KEY=$(docker compose exec "$TARGET_HOST" curl --silent --user "$CONJUR_USER:$CONJUR_PASSWORD" -k "https://$TARGET_HOST/authn/$CONJUR_ACCOUNT/login")
-  docker compose exec "$TARGET_HOST" curl \
-        --max-time 3 \
-        --silent \
-        --insecure \
-        --request POST \
-        --data "$API_KEY" \
-        "https://$TARGET_HOST/authn/$CONJUR_ACCOUNT/$CONJUR_USER/authenticate" | base64 | tr -d "[:space:]"
-}
+  follower_pod="$1"
 
-get_secret_from_follower() {
-  local follower_hostname="$1"
-  local secret_id="$2"
-  local token="$3"
-
-  docker compose exec "$DOCKER_LEADER_CONTAINER" sh -c "
+  API_KEY=$(bin/kubectl "exec $follower_pod -n '$(_get_k8s_follower_namespace)' -c conjur -- bash -c 'curl --silent --user "$CONJUR_USER:$CONJUR_PASSWORD" -k "http://$FOLLOWER_HOSTNAME/authn/$CONJUR_ACCOUNT/login"'")
+  
+  bin/kubectl "exec $follower_pod -n '$(_get_k8s_follower_namespace)' -c conjur -- bash -c ' \
     curl \
       --max-time 3 \
       --silent \
       --insecure \
-      --header 'Authorization: Token token=\"$token\"' \
-      https://$follower_hostname/secrets/$CONJUR_ACCOUNT/variable/$secret_id
+      --request POST \
+      --data $API_KEY \
+      "http://$FOLLOWER_HOSTNAME/authn/$CONJUR_ACCOUNT/$CONJUR_USER/authenticate"
+  '| base64 | tr -d \"[:space:]\""
+}
+
+get_secret_from_follower() {
+  local follower_pod="$1"
+  local secret_id="$2"
+  local token="$3"
+  local command
+
+  command="
+    curl \
+      --max-time 3 \
+      --silent \
+      --insecure \
+      --header \"Authorization: Token token=\\\"$token\\\"\" \
+      http://$FOLLOWER_HOSTNAME/secrets/$CONJUR_ACCOUNT/variable/$secret_id
   "
+
+  bin/kubectl "exec '$follower_pod' -n '$(_get_k8s_follower_namespace)' -c conjur -- bash -c '$command'"
 }
 
 while true ; do
